### ISSUE TITLE
Wrong index calculation in spoj_GSS1.cpp 

### ISSUE THREAD

**Issue by babhishek21** [kartikkukreja/blog-codes#1]
In [spoj_GSS1.cpp](https://github.com/kartikkukreja/blog-codes/blob/master/src/spoj_GSS1.cpp) at line 56, shouldn't `int left = 2*stIndex+1` and `int right = 2*stIndex+2` ? Since you are following a zero based indexing system, your calculation would not leave space for the root of the tree.

**Comment by kartikkukreja** [comment]
left and right are segment tree indices and are 1-based. The indices of segment tree itself are 1-based, however the input array it is built for is 0-based. In the constructor at line 33, you will find that buildTree is called with stIndex = 1 (segment tree index of root) and lo = 0, hi = N-1 (input array range).

This is the usual convention with segment trees (1-based tree but 0-based input array).

**Comment by babhishek21** [comment]
Thanks for the reply. Just out of curiosity in line 81, you already have the minimum valid value of N required to build your tree when the loop ends. Why double it one more time before returning?

**Comment by kartikkukreja** [comment]
The segment tree size for an array of size N is x*2, where x is the smallest power of 2 which is greater than or equal to N. When the loop ends, we have x, then we double it to get the segment tree size. I hope that explains it.

**Comment by babhishek21** [comment]
Aaah.. sorry my bad. So basically that little piece of code is returning
`2* pow(2, ceil(log2(N))` . I completely forgot about the 2*x length requirement. Thank you.
